services: 
  node:
    build:
      context: node
      dockerfile: Dockerfile.prod
    container_name: node
    volumes:
      - ./node:/usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s sh -c 'npm install && npm start;'
    networks: 
      - fullcycle
    tty: true
    depends_on:
       - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    tty: true
    networks: 
      - fullcycle
    ports: 
      - "8080:80"
    depends_on:
       - node
       - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - fullcycle

networks:
  fullcycle:
    driver: bridge
